Repository ucsb-cs156-s22/s22-6pm-courses, pull requests merged in 2022-06, with the labels that each got.

#57 s22-6pm-2 Nirmit Method for Section information given enroll code and quarter
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBCurriculumServiceTests.java
Labels: s22-6pm-2, 10

#31 s22-6pm-2 Yufei Backend API get courses by psId
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalCoursesController.java
  src/main/java/edu/ucsb/cs156/courses/repositories/PersonalCoursesRepository.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalCoursesControllerTests.java
Labels: s22-6pm-2, 10

#43 S22-6pm-1 Zach added a table component that displays course with sections info
  frontend/src/fixtures/sectionsFixtures.js
  frontend/src/main/components/Courses/CoursesWithSectionsTable.js
  frontend/src/main/utils/CoursesWithSectionsUtilities.js
  frontend/src/main/utils/quarterUtilities.js
  frontend/src/stories/components/Courses/CoursesWithSectionsTable.stories.js
  frontend/src/tests/components/Courses/CoursesWithSectionsTable.test.js
  frontend/src/tests/utils/CoursesWithSectionsUtilities.test.js
  frontend/src/tests/utils/quarterUtilities.test.js
Labels: s22-6pm-1, 10, :+1: Peer CR Done

#59 s22-6pm-1 Anuragh fixed red lines in npm test
  frontend/src/tests/components/BasicCourseSearch/BasicCourseSearchForm.test.js
  frontend/src/tests/components/Subjects/SingleSubjectDropdown.test.js
  frontend/src/tests/pages/HomePage.test.js
Labels: s22-6pm-1, 10, :+1: Peer CR Done, :gear: Waiting on CI/CD to merge

#53 s22-6pm-1 created fixtures for section table
  frontend/src/fixtures/sectionFixtures.js
Labels: s22-6pm-1, 5

#48 s22-6pm-1 - Added Section Search Table to Section Search Page
  frontend/src/fixtures/sectionsFixtures.js
  frontend/src/main/components/Courses/CoursesWithSectionsTable.js
  frontend/src/main/pages/SectionSearch/SectionSearchIndexPage.js
  frontend/src/main/utils/CoursesWithSectionsUtilities.js
  frontend/src/main/utils/quarterUtilities.js
  frontend/src/stories/components/Courses/SectionSearchTable.stories.js
  frontend/src/tests/pages/SectionSearch/SectionSearchIndexPage.test.js
  frontend/src/tests/utils/CoursesWithSectionsUtilities.test.js
Labels: s22-6pm-1, 10

#73 s22-6pm-1 Kevin - increased timeout for stryker github action
  .github/workflows/34-frontend-mutation-testing.yml
Labels: s22-6pm-1

#51 s22-6pm-2 Mikey Added Placeholder page and dynamic routing for personal schedules.
  frontend/src/App.js
  frontend/src/main/components/PersonalSchedules/PersonalSchedulesTable.js
  frontend/src/main/pages/PersonalSchedules/PersonalScheduleInfoPage.js
  frontend/src/main/utils/useBackend.js
  frontend/src/tests/pages/PersonalSchedules/PersonalScheduleInfoPage.test.js
  frontend/stryker.conf.json
Labels: s22-6pm-2, 5, :+1: Peer CR Done, :gear: Waiting on CI/CD to merge

#68 s22-6pm-2 Yufei replace stub with course search service
  src/main/java/edu/ucsb/cs156/courses/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalCoursesController.java
  src/main/java/edu/ucsb/cs156/courses/errors/CourseNotFoundException.java
  src/main/java/edu/ucsb/cs156/courses/errors/InvalidEnrollCdException.java
  src/main/java/edu/ucsb/cs156/courses/errors/InvalidPsIdException.java
  src/main/java/edu/ucsb/cs156/courses/errors/InvalidQuarterException.java
  src/main/java/edu/ucsb/cs156/courses/repositories/PersonalScheduleRepository.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalCoursesControllerTests.java
Labels: s22-6pm-2

#63 s22-6pm-1 Aaditya updated section search table to distinguish between Lectures and Sections
  frontend/src/App.js
  frontend/src/main/components/Courses/CoursesWithSectionsTable.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/SectionSearch/SectionSearchIndexPage.js
  frontend/src/main/utils/CoursesWithSectionsUtilities.js
  frontend/src/tests/components/Courses/CoursesWithSectionsTable.test.js
  frontend/src/tests/pages/SectionSearch/SectionSearchIndexPage.test.js
  frontend/src/tests/utils/CoursesWithSectionsUtilities.test.js
Labels: s22-6pm-1, :+1: Peer CR Done

#65 s22-6pm-1 Aaditya updated section search with new api
  frontend/src/fixtures/newsectionFixtures.js
  frontend/src/main/components/Courses/CoursesWithSectionsTable.js
  frontend/src/main/pages/SectionSearch/SectionSearchIndexPage.js
  frontend/src/main/utils/CoursesWithSectionsUtilities.js
  frontend/src/stories/components/Courses/SectionSearchTable.stories.js
  frontend/src/tests/components/Courses/CoursesWithSectionsTable.test.js
  frontend/src/tests/pages/SectionSearch/SectionSearchIndexPage.test.js
  frontend/src/tests/utils/CoursesWithSectionsUtilities.test.js
Labels: s22-6pm-1, :+1: Peer CR Done

#84 Sid 6 pm 2- Clean PR for get Enroll Cds
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalCoursesController.java
  src/main/java/edu/ucsb/cs156/courses/entities/PersonalCourses.java
  src/main/java/edu/ucsb/cs156/courses/repositories/PersonalCoursesRepository.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalCoursesControllerTests.java
Labels: s22-6pm-2, :+1: Peer CR Done

#75 s22-6pm-1 Changed Example on the Navbar to Course Search
  frontend/src/main/components/Nav/AppNavbar.js
Labels: s22-6pm-1, :+1: Peer CR Done
