Repository ucsb-cs156-s22/s22-6pm-courses, pull requests merged in 2022-05, with the labels that each got.

#13 Zach CodeCov
  README.md
Labels: s22-6pm-1, 5

#15 6pm-2 Add link to QA for 6pm-2
  README.md
Labels: s22-6pm-2, 5

#21 6pm-2 Heroku Production Deployment
  README.md
  src/main/java/edu/ucsb/cs156/courses/controllers/CSRFController.java
Labels: s22-6pm-2, 10

#24 am - add entity and repository file for db table
  src/main/java/edu/ucsb/cs156/courses/entities/PersonalCourses.java
  src/main/java/edu/ucsb/cs156/courses/repositories/PersonalCoursesRepository.java
Labels: s22-6pm-2

#23 6pm-1 Heroku QA deployment
  README.md
Labels: s22-6pm-1

#22 s22-6pm-1 - Update README with the links to storyboard docs and docsQA - Closes #1
  README.md
Labels: s22-6pm-1, Merge Candidate

#26 s22-6pm-2 Yufei backend API Add a Course to Personal Course Database
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalCoursesController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalCoursesControllerTests.java
Labels: s22-6pm-2, Merge Candidate, :question: Ready for Staff Review, :interrobang: FIXME-cr-requested-changes

#25 s22-6pm-1 Anuragh - added Section search drop-down menu to the navbar
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/SectionSearch/SectionSearchIndexPage.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/SectionSearch/SectionSearchIndexPage.test.js
Labels: s22-6pm-1, 10

#29 s22-6pm-2 Yufei List All Courses API
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalCoursesController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalCoursesControllerTests.java
Labels: s22-6pm-2, 10

#39 s22-6pm-1 Kevin - Added .DS_Store to gitignore file
  .gitignore
Labels: s22-6pm-1

#41 s22-6pm-1 Kevin - Merged *new* starter code which makes handling course jsons easier
  src/main/java/edu/ucsb/cs156/courses/documents/ConvertedSection.java
  src/main/java/edu/ucsb/cs156/courses/documents/Course.java
  src/main/java/edu/ucsb/cs156/courses/documents/CourseInfo.java
  src/main/java/edu/ucsb/cs156/courses/documents/CoursePage.java
  src/main/java/edu/ucsb/cs156/courses/documents/FinalExam.java
  src/main/java/edu/ucsb/cs156/courses/documents/GeneralEducation.java
  src/main/java/edu/ucsb/cs156/courses/documents/Instructor.java
  src/main/java/edu/ucsb/cs156/courses/documents/Section.java
  src/main/java/edu/ucsb/cs156/courses/documents/TimeLocation.java
  src/main/java/edu/ucsb/cs156/courses/entities/PersonalSchedule.java
  src/main/java/edu/ucsb/cs156/courses/entities/UCSBSubject.java
  src/main/java/edu/ucsb/cs156/courses/entities/User.java
  src/main/java/edu/ucsb/cs156/courses/models/CurrentUser.java
  src/main/java/edu/ucsb/cs156/courses/models/SystemInfo.java
  src/main/java/edu/ucsb/cs156/courses/services/UCSBCurriculumService.java
  src/test/java/edu/ucsb/cs156/courses/documents/CoursePageFixtures.java
  src/test/java/edu/ucsb/cs156/courses/documents/CoursePageTests.java
  src/test/java/edu/ucsb/cs156/courses/services/UCSBCurriculumServiceTests.java
Labels: s22-6pm-1, :+1: Peer CR Done

#42 s22-6pm-1 Kevin - Add API endpoint for getting course information with detailed section info in a useable form.
  src/main/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/UCSBCurriculumControllerTests.java
Labels: s22-6pm-1, Merge Candidate, :+1: Peer CR Done, :gear: Waiting on CI/CD to merge
